# Generated by Django 6.0 on 2026-02-23 17:12

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.CustomUserManager()),
                ('all_objects', user.models.AllObjectsUserManager()),
            ],
        ),
    ]
